services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    environment:
      - PORT=3000
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  backend_modules:
  frontend_modules:
